Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -43,7 +43,7 @@ jobs:
       - name: Set Environment Variables
         if: ${{ steps.checkReleaseTag.outputs.exists == 'false' }}
         run: |
-          echo "zipFile=${{ env.packageFileName }}_v${{ steps.version.outputs.value }}_VPM".zip >> $GITHUB_ENV
+          echo "zipFile=${{ env.packageFileName }}_v${{ steps.version.outputs.value }}_VPM.zip" >> $GITHUB_ENV
           echo "unityPackage=${{ env.packageFileName }}_v${{ steps.version.outputs.value }}.unitypackage" >> $GITHUB_ENV
     
       - name: Set ZIP Url
@@ -75,8 +75,19 @@ jobs:
           filename: "../../${{env.zipFile}}" # make the zip file two directories up, since we start two directories in above
           exclusions: "*.git* *.github* .gitignore Packages/"
           
-      - run: find "${{env.packagePath}}" -name \*.meta >> metaList
+      - name: Generate meta files list
         if: ${{ steps.checkReleaseTag.outputs.exists == 'false' }}
+        run: find "${{env.packagePath}}" -name \*.meta >> metaList
+          
+      - name: Debug paths
+        if: ${{ steps.checkReleaseTag.outputs.exists == 'false' }}
+        run: |
+          pwd
+          ls -la
+          echo "Meta files content:"
+          cat metaList
+          echo "Package path contents:"
+          ls -la "${{env.packagePath}}"
           
       - name: Create UnityPackage
         if: ${{ steps.checkReleaseTag.outputs.exists == 'false' }}
@@ -84,6 +95,17 @@ jobs:
         with:
           package-path: ${{ env.unityPackage }}
           include-files: metaList
+          
+      - name: Verify UnityPackage
+        if: ${{ steps.checkReleaseTag.outputs.exists == 'false' }}
+        run: |
+          ls -la
+          if [ ! -f "${{ env.unityPackage }}" ]; then
+            echo "ERROR: Unity package file not found at expected path: ${{ env.unityPackage }}"
+            exit 1
+          else
+            echo "Unity package file successfully created at: ${{ env.unityPackage }}"
+          fi
           
       - name: Add Icon to UnityPackage
         if: ${{ steps.checkReleaseTag.outputs.exists == 'false' }}
@@ -100,7 +122,7 @@ jobs:
         uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
         with:
           name: "${{ env.packageReleaseName }} v${{ steps.version.outputs.value }}"
-          tag_name: "v${{ steps.version.outputs.value }}"
+          tag_name: "${{ steps.tag.outputs.prop }}"
           files: |
             ${{ env.zipFile }}
             ${{ env.unityPackage }}
